runtime: go
api_version: go1
handlers:
  - url:  /.*
    script: _go_app
  - url: /(.*\.(gif|png|jpg))$
    static_files: build/
    upload: static/.*\.(gif|png|jpg)$
skip_files:
  - ^(.*/)?.*/src/.*$
  - ^(.*/)?.*/public/.*$
  - ^node_modules$